max_locations_per_request: 10000
access_control_allow_origin: '*'

datasets:
- name: eudem25m
  path: data/eudem-vrt/

- name: mapzen
  path: data/mapzen/

- name: eu-global
  child_datasets:
    - eudem25m
    - mapzen
